name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-04-05"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "0272397b-4294-4a6b-83ac-bb0458bd1090"
